### ISSUE TITLE
FEFAST - How to use?

### ISSUE THREAD

**Issue by cesarvargas00** [ferrumfix/ferrumfix#8]
Hi, first of all, thank you very much for your effort on making this library! 
Send me your wallet so I can buy you a pizza 🍕 🍺 .

So, I'm trying to use this library to read data from the Brazillian Stock Exchange (B3), but I'm kinda of new in the ~~Wayne's~~ Rust World.

Could you help me pointing out with an example that uses `fefast`?

**Comment by neysofu** [comment]
Hi @cesarvargas00! Thank you a lot for your interest in FerrumFIX :smiley: 

`fefast` is still in development and I'm afraid there's nothing I can help you with for now. I've been focusing on FIX as that's by far the most requested protocol. You can take a look at the `fefast` sources to get an idea on how to roll your own, but you'll only find bits and pieces.

You can still send me a tip if you feel like it. I'm waiting for the Sponsor status by GitHub so that I can make this easier for those interested!

For now, you can send an Algorand tip at `DQTRAXCXQM5GGQ65VESJ5ZYQHXXVBOJQJZBLZZSWC6YCFAERIBWRICUSFY` :pray:
