### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by DonghunLouisLee** [ferrumfix/ferrumfix#9]
First of all, thanks for making this library. I'm currently trying to create a FIX engine in rust and this library has been most helpful so far! 

I was looking at the examples in but found some of them not working as expected(some even not compiling) such as https://github.com/ferrumfix/ferrumfix/blob/develop/examples/20_tokio_fix_initiator/src/main.rs 
It seems that in 0.7.0 fefix::session::FixConnection was removed due to some reason. Would it be possible to know why? 

And since fix::session::Backend trait it's genuine trait instead of async_trait, I'm presuming there are specific design patterns for FIX Engines in the future such as creating a socket acceptor in a tokio task and forwarding all messages to a different task via a channel? It would be great to know what you are planning and how I could help! 

Thanks again for creating this library!

**Comment by neysofu** [comment]
Hi! Thank you for reading through the code and providing feedback!

I decided to momentarily remove `fefix::session::FixConnection` because it's not ready yet. Mind you, it's the single feature I'm most dedicated to, so it'll be back in some future version once I've made some progress. Before 0.7.0, `FixConnection` was always there yet broken and I think it's better to be more direct in showing my users what I consider to be ready to use and what is not. This is also the reason why some examples using it may be momentarily commented out!

As for `async_trait` - you're right, it would be so much simpler. Unfortunately, it costs one allocation per function call which is quite expensive. For the foreseeable future, the `Backend` / `Application` type (I haven't settled on a name yet) will not be `async` and users will have to either use a thread pool or e.g. explicitly enter a Tokio `Runtime`. It's a bit annoying, but it'll work and it will flexible enough for almost any use case.

Long  term, we want to provide a middleware API so that users can build abstractions on top of `Backend`. Some examples might be:
- Log all incoming and outgoing messages.
- Store all messages in a DB.
- Add some FIX field in the header of all outgoing messages, before they're sent out.
- Build your application against an `AsyncBackend` wrapper, rather than directly against `Backend`.

The specific pattern via channels that you mentioned will be possible!

Thank you for offering to help! I don't think I'll be able to accept contributions to the core at the moment (it takes a lot of energy and things are mature enough yet), but our documentation could definitely use some help. You can try to build docs on your machine with `RUSTDOCFLAGS="--cfg doc_cfg" cargo +nightly doc --all-features --open`. You'll get warnings about missing documentation items and you can start from there. You can get a sense of what kind of writing style I'm going for by looking at what I've written so far.

**Comment by DonghunLouisLee** [comment]
@neysofu Sounds all good. This project definitely has a lot of potentials and I cannot wait to see how great this can become. In the meantime, since I'm currently looking for a ready-to-use library for FIX engines, I'll use https://github.com/jbendig/fix-rs for a simple poc product I'm working on. Hopefully, this project becomes production ready so that I'll be able to swith FIX library to this in the near future. 

Thanks again for staring on this project.
